name: build-and-release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write # Allow the job to push commits and tags

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true # Retain credentials for git push

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build # Outputs to /dist

      - name: Extract tag name
        id: extract_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Attach dist to the tag commit
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -f dist  # Force-add dist, overriding .gitignore
          git commit -m "build(dist): include artefacts for $TAG_NAME [skip ci]"

          git tag -fa "$TAG_NAME" -m "$TAG_NAME"  # Move tag to new commit
          git push --force origin HEAD:refs/tags/$TAG_NAME

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
