name: build-and-release

on:
  push:
    tags: ['v*.*.*'] # only real semver tags

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 } # we need the tag object

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - run: npm ci
      - run: npm run build # must output to /dist

      # ──────────────────────────────────────────────────────────────
      - name: Attach dist to the tag commit
        env:
          TAG_NAME: ${{ github.ref_name }} # e.g. v1.2.3
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 1. add artefacts, overriding .gitignore
          git add -f dist
          git commit -m "build(dist): include artefacts for $TAG_NAME [skip ci]"

          # 2. move the tag to this new commit
          git tag -fa "$TAG_NAME" -m "$TAG_NAME"

          # 3. fast-push the updated ref → no separate branch needed
          git push --force origin HEAD:refs/tags/$TAG_NAME
      # ──────────────────────────────────────────────────────────────
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
